/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_test_7 (
    input clk,
    input rst,
    input [5:0] alufn,
    input disrupiton,
    input button,
    output reg out,
    output reg [6:0] led
  );
  
  
  
  wire [16-1:0] M_alu__out;
  reg [6-1:0] M_alu__alufn;
  reg [16-1:0] M_alu__x;
  reg [16-1:0] M_alu__y;
  alu_6 alu_ (
    .alufn(M_alu__alufn),
    .x(M_alu__x),
    .y(M_alu__y),
    .out(M_alu__out)
  );
  
  reg [15:0] x;
  reg [15:0] y;
  reg [15:0] ans;
  reg not_working;
  
  localparam S0_state = 2'd0;
  localparam S1_state = 2'd1;
  localparam S2_state = 2'd2;
  localparam S3_state = 2'd3;
  
  reg [1:0] M_state_d, M_state_q = S0_state;
  
  always @* begin
    M_state_d = M_state_q;
    
    x = 1'h0;
    y = 1'h0;
    led = 7'h00;
    ans = 1'h0;
    not_working = 1'h1;
    
    case (alufn)
      6'h00: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 16'h0154;
              y = 16'h0134;
              ans = 16'h0288;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            led = 7'h20;
            if (button) begin
              M_state_d = S2_state;
            end else begin
              x = 16'h7fff;
              y = 16'h0001;
              ans = 16'h8000;
              M_state_d = S1_state;
            end
          end
          S2_state: begin
            led = 7'h10;
            if (button) begin
              M_state_d = S3_state;
            end else begin
              x = 16'h01f4;
              y = 16'hfd55;
              ans = 16'hff49;
              M_state_d = S2_state;
            end
          end
          S3_state: begin
            led = 7'h08;
            if (button) begin
              M_state_d = S0_state;
            end else begin
              x = 16'h8000;
              y = 16'h8000;
              ans = 16'h0000;
              M_state_d = S3_state;
            end
          end
        endcase
      end
      6'h01: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 16'h0080;
              y = 16'h0001;
              ans = 16'h007f;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            led = 7'h20;
            if (button) begin
              M_state_d = S2_state;
            end else begin
              x = 16'h0000;
              y = 16'h0000;
              ans = 16'h0000;
              M_state_d = S1_state;
            end
          end
          S2_state: begin
            led = 7'h10;
            if (button) begin
              M_state_d = S3_state;
            end else begin
              x = 16'h4000;
              y = 16'h8000;
              ans = 16'hc000;
              M_state_d = S2_state;
            end
          end
          S3_state: begin
            led = 7'h08;
            if (button) begin
              M_state_d = S0_state;
            end else begin
              x = 16'h8001;
              y = 16'h8001;
              ans = 16'h0000;
              M_state_d = S3_state;
            end
          end
        endcase
      end
      6'h02: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 16'hffff;
              ans = 16'h0001;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            led = 7'h20;
            if (button) begin
              M_state_d = S0_state;
            end else begin
              x = 16'h400a;
              ans = 16'h400a;
              M_state_d = S1_state;
            end
          end
          S2_state: begin
            M_state_d = S0_state;
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      6'h04: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 16'h4024;
              ans = 16'h4025;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            led = 7'h20;
            if (button) begin
              M_state_d = S0_state;
            end else begin
              x = 16'h7fff;
              ans = 16'h8000;
              M_state_d = S1_state;
            end
          end
          S2_state: begin
            M_state_d = S0_state;
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      6'h18: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 50'h396ae77e4f312;
              y = 50'h3e88b526b690c;
              ans = 50'h38d95edd60268;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            M_state_d = S0_state;
          end
          S2_state: begin
            M_state_d = S0_state;
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      6'h1e: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 50'h396ae77e4f312;
              y = 50'h3e88b526b690c;
              ans = 50'h3f1a3dc7a59b6;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            M_state_d = S0_state;
          end
          S2_state: begin
            M_state_d = S0_state;
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      6'h16: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 50'h396ae77e4f312;
              y = 50'h3e88b526b690c;
              ans = 47'h640deea4574e;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            M_state_d = S0_state;
          end
          S2_state: begin
            M_state_d = S0_state;
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      6'h17: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 50'h396ae77e4f312;
              y = 50'h3e88b526b690c;
              ans = 47'h64f6c93f6f5f;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            M_state_d = S0_state;
          end
          S2_state: begin
            M_state_d = S0_state;
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      6'h1c: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 50'h396ae77e4f312;
              y = 50'h3e88b526b690c;
              ans = 50'h3e88b526b690c;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            M_state_d = S0_state;
          end
          S2_state: begin
            M_state_d = S0_state;
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      6'h19: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 50'h396ae77e4f312;
              y = 50'h3e88b526b690c;
              ans = 50'h38e7ec8711a79;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            M_state_d = S0_state;
          end
          S2_state: begin
            M_state_d = S0_state;
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      6'h1a: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 50'h396ae77e4f312;
              y = 50'h3e88b526b690c;
              ans = 50'h396ae77e4f312;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            M_state_d = S0_state;
          end
          S2_state: begin
            M_state_d = S0_state;
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      6'h06: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 27'h6054ab4;
              y = 1'h0;
              ans = 1'h0;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            led = 7'h20;
            if (button) begin
              M_state_d = S2_state;
            end else begin
              x = 47'h650e124ef1c7;
              y = 4'hb;
              ans = 47'h650e124ef1bd;
              M_state_d = S1_state;
            end
          end
          S2_state: begin
            led = 7'h10;
            if (button) begin
              M_state_d = S3_state;
            end else begin
              x = 4'hb;
              y = 50'h3f28cb71571c7;
              ans = 50'h3f28cb71571bd;
              M_state_d = S2_state;
            end
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      6'h06: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 27'h6054ab4;
              y = 1'h0;
              ans = 1'h0;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            led = 7'h20;
            if (button) begin
              M_state_d = S2_state;
            end else begin
              x = 47'h650e124ef1c7;
              y = 4'hb;
              ans = 47'h650e124ef1bd;
              M_state_d = S1_state;
            end
          end
          S2_state: begin
            led = 7'h10;
            if (button) begin
              M_state_d = S3_state;
            end else begin
              x = 4'hb;
              y = 50'h3f28cb71571c7;
              ans = 50'h3f28cb71571bd;
              M_state_d = S2_state;
            end
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      6'h28: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 7'h6f;
              y = 1'h0;
              ans = 50'h3f28cb71571c7;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            led = 7'h20;
            if (button) begin
              M_state_d = S2_state;
            end else begin
              x = 24'h9a2112;
              y = 27'h606ae2d;
              ans = 1'h1;
              M_state_d = S1_state;
            end
          end
          S2_state: begin
            led = 7'h10;
            if (button) begin
              M_state_d = S3_state;
            end else begin
              x = 17'h1b1a2;
              y = 50'h3f18a09ba0a4e;
              ans = 1'h0;
              M_state_d = S2_state;
            end
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      6'h2c: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 7'h6f;
              y = 1'h0;
              ans = 50'h3f28cb71571c7;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            led = 7'h20;
            if (button) begin
              M_state_d = S2_state;
            end else begin
              x = 24'h9a2112;
              y = 27'h606ae2d;
              ans = 1'h1;
              M_state_d = S1_state;
            end
          end
          S2_state: begin
            led = 7'h10;
            if (button) begin
              M_state_d = S3_state;
            end else begin
              x = 17'h1b1a2;
              y = 50'h3f18a09ba0a4e;
              ans = 1'h0;
              M_state_d = S2_state;
            end
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      6'h20: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 16'h22e4;
              y = 16'h0003;
              ans = 16'h1720;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            led = 7'h20;
            if (button) begin
              M_state_d = S2_state;
            end else begin
              x = 16'hcf2c;
              y = 16'h0003;
              ans = 16'h7960;
              M_state_d = S1_state;
            end
          end
          S2_state: begin
            M_state_d = S0_state;
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      6'h21: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 16'h22e4;
              y = 16'h0003;
              ans = 16'h045c;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            led = 7'h20;
            if (button) begin
              M_state_d = S2_state;
            end else begin
              x = 16'hcf2c;
              y = 16'h0003;
              ans = 16'h19e5;
              M_state_d = S1_state;
            end
          end
          S2_state: begin
            M_state_d = S0_state;
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      6'h23: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 16'h22e4;
              y = 16'h0003;
              ans = 16'h045c;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            led = 7'h20;
            if (button) begin
              M_state_d = S2_state;
            end else begin
              x = 16'hcf2c;
              y = 16'h0003;
              ans = 16'hf9e5;
              M_state_d = S1_state;
            end
          end
          S2_state: begin
            M_state_d = S0_state;
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      6'h33: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 16'h0154;
              y = 16'h0007;
              ans = 16'h0000;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            led = 7'h20;
            if (button) begin
              M_state_d = S2_state;
            end else begin
              x = 16'h0154;
              y = 16'h0154;
              ans = 16'h0001;
              M_state_d = S1_state;
            end
          end
          S2_state: begin
            led = 7'h10;
            if (button) begin
              M_state_d = S3_state;
            end else begin
              x = 16'h0007;
              y = 16'h0154;
              ans = 16'h0000;
              M_state_d = S2_state;
            end
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      6'h35: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 16'h0154;
              y = 16'h0007;
              ans = 16'h0000;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            led = 7'h20;
            if (button) begin
              M_state_d = S2_state;
            end else begin
              x = 16'h0154;
              y = 16'h0154;
              ans = 16'h0000;
              M_state_d = S1_state;
            end
          end
          S2_state: begin
            led = 7'h10;
            if (button) begin
              M_state_d = S3_state;
            end else begin
              x = 16'h0007;
              y = 16'h0154;
              ans = 16'h0001;
              M_state_d = S2_state;
            end
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      6'h37: begin
        not_working = 1'h0;
        
        case (M_state_q)
          S0_state: begin
            led = 7'h40;
            if (button) begin
              M_state_d = S1_state;
            end else begin
              x = 16'h0154;
              y = 16'h0007;
              ans = 16'h0000;
              M_state_d = S0_state;
            end
          end
          S1_state: begin
            led = 7'h20;
            if (button) begin
              M_state_d = S2_state;
            end else begin
              x = 16'h0154;
              y = 16'h0154;
              ans = 16'h0001;
              M_state_d = S1_state;
            end
          end
          S2_state: begin
            led = 7'h10;
            if (button) begin
              M_state_d = S3_state;
            end else begin
              x = 16'h0007;
              y = 16'h0154;
              ans = 16'h0001;
              M_state_d = S2_state;
            end
          end
          S3_state: begin
            M_state_d = S0_state;
          end
        endcase
      end
      default: begin
        x = 16'hb576;
        y = 16'h0000;
        ans = 16'hbb77;
      end
    endcase
    M_alu__alufn = alufn;
    M_alu__x = x;
    M_alu__y = y;
    if (disrupiton) begin
      if ((M_alu__out[1+13-:14] == ans[1+13-:14]) && (ans[15+0-:1] == 1'h0) & (ans[0+0-:1] == 1'h0) && (not_working == 1'h0)) begin
        out = 1'h1;
      end else begin
        out = 1'h0;
      end
    end else begin
      out = M_alu__out == ans;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
