/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module sixteen_bit_increment_14 (
    input [15:0] x,
    output reg [15:0] s
  );
  
  
  
  wire [16-1:0] M_sixteenbitadder_s;
  wire [1-1:0] M_sixteenbitadder_z;
  wire [1-1:0] M_sixteenbitadder_v;
  wire [1-1:0] M_sixteenbitadder_n;
  reg [1-1:0] M_sixteenbitadder_alufn;
  reg [16-1:0] M_sixteenbitadder_x;
  reg [16-1:0] M_sixteenbitadder_y;
  sixteen_bit_adder_11 sixteenbitadder (
    .alufn(M_sixteenbitadder_alufn),
    .x(M_sixteenbitadder_x),
    .y(M_sixteenbitadder_y),
    .s(M_sixteenbitadder_s),
    .z(M_sixteenbitadder_z),
    .v(M_sixteenbitadder_v),
    .n(M_sixteenbitadder_n)
  );
  
  always @* begin
    M_sixteenbitadder_x = x;
    M_sixteenbitadder_y = 16'h0001;
    M_sixteenbitadder_alufn = 1'h0;
    s = M_sixteenbitadder_s;
  end
endmodule
